In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
sns.set_theme(style="whitegrid")
print("All libraries imported successfully!")

All libraries imported successfully!

In [8]:
orders=pd.read_csv("orders.csv")
products=pd.read_csv("products.csv")
customers=pd.read_csv("customers.csv")
delivery=pd.read_csv("delivery.csv")
returns=pd.read_csv("returns.csv")
print("All datasets loaded successfully!")

All datasets loaded successfully!

In [10]:
datasets = {
    "Orders":orders,
    "Products":products,
    "Customers":customers,
    "Delivery":delivery,
    "Returns":returns
}

for name, data in datasets.items():
    print(f"{name}:{data.shape}")

Orders: (1008, 8)
Products: (90, 7)
Customers: (320, 5)
Delivery: (620, 4)
Returns: (1000, 5)

In [11]:
for name, data in datasets.items():
    print(f"\n===== {name.upper()} =====")
    display(data.head())

===== ORDERS =====

,order_id,order_item_id,product_id,customer_id,order_date,quantity,price,discount
0,O00041,OI000001,P0076,C0254,2026-02-20,3,8629.90,0.305
1,O00064,OI000002,P0040,C0317,2025-08-29,2,554.06,0.461
2,O00196,OI000003,P0026,C0123,2025-06-01,2,314.22,0.154
3,O00503,OI000004,P0089,C0183,2026-06-22,3,794.92,0.103
4,O00348,OI000005,P0058,C0032,2025-04-20,1,5514.24,0.126

===== PRODUCTS =====

,product_id,category,brand,size,seller_id,seller,list_price
0,P0001,Beauty,UrbanLeaf,M,S004,Delta Direct,563.63
1,P0002,Apparel,PeakPro,small,S018,Riverstone Store,452.23
2,P0003,Footwear,UrbanLeaf,XS,S003,Cedar Commerce,764.07
3,P0004,Electronics,Aster,L,S004,Delta Direct,13364.50
4,P0005,Apparel,Aster,S,S017,QuickBuy Hub,1510.07

===== CUSTOMERS =====

  customer_id region  previous_orders customer_since order_history
0       C0001  South                8     2024-03-06        Repeat
1       C0002  South                3     2024-11-02        Repeat
2       C0003   West                4     2023-09-13        Repeat
3       C0004   West                2     2022-01-22        Repeat
4       C0005  South                5     2024-06-04        Repeat

===== DELIVERY =====

  order_id promised_date delivered_date           courier
0   O00001    2025-09-22     2025-09-20  National Express
1   O00002    2026-06-06     2026-06-09         TrackFast
2   O00003    2025-03-27     2025-03-28         TrackFast
3   O00004    2025-10-07     2025-10-08  National Express
4   O00005    2026-03-06     2026-03-07  National Express

===== RETURNS =====

  order_item_id order_id  return_flag            reason return_date
0      OI000001   O00041            0               NaN         NaN
1      OI000002   O00064            1  Not as described  2025-09-21
2      OI000003   O00196            0               NaN         NaN
3      OI000004   O00503            0               NaN         NaN
4      OI000005   O00348            0               NaN         NaN

In [12]:
for name, data in datasets.items():
    print(f"\n===== {name.upper()} =====")
    data.info()

===== ORDERS =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1008 non-null   object
 1   order_item_id  1008 non-null   object
 2   product_id     1008 non-null   object
 3   customer_id    1008 non-null   object
 4   order_date     1008 non-null   object
 5   quantity       1008 non-null   int64
 6   price          1008 non-null   float64
 7   discount       1008 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 63.1+ KB

===== PRODUCTS =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  90 non-null     object
 1   category    90 non-null     object
 2   brand       90 non-null     object
 3   size        90 non-null     object
 4   seller_id   90 non-null     object
 5   seller      90 non-null     object
 6   list_price  90 non-null     float64
dtypes: float64(1), object(6)
memory usage: 5.1+ KB

===== CUSTOMERS =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      320 non-null    object
 1   region           315 non-null    object
 2   previous_orders  320 non-null    int64
 3   customer_since   320 non-null    object
 4   order_history    320 non-null    object
dtypes: int64(1), object(4)
memory usage: 12.6+ KB

===== DELIVERY =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        620 non-null    object
 1   promised_date   620 non-null    object
 2   delivered_date  620 non-null    object
 3   courier         620 non-null    object
dtypes: object(4)
memory usage: 19.5+ KB

===== RETURNS =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  1000 non-null   object
 1   order_id       1000 non-null   object
 2   return_flag    1000 non-null   int64
 3   reason         245 non-null    object
 4   return_date    270 non-null    object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB